### ISSUE TITLE
Server Machine Dataset description

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [smallcowbaby/OmniAnomaly#11]
Could you please give me the original dataset of "server machine" dataset? Or please describe how first the data looks like?
I have no idea how the data looks like. I opened one file in `train folder`
Here is the first line of the file: 
`0.032258,0.039195,0.027871,0.024390,0.000000,0.915385,0.343691,0.000000,0.020011,0.000122,0.106312,0.081081,0.027397,0.060266,0.085018,0.122516,0.000000,0.000000,0.062195,0.041221,0.043242,0.031607,0.533195,0.010224,0.011195,0.009274,0.000000,0.036625,0.000000,0.004298,0.029993,0.022131,0.000000,0.000045,0.034677,0.034747,0.000000,0.000000`

**Comment by NiuChH** [comment]
Hi, I will see if it’s possible to reveal the original data. But the basic idea is that each row stands for the information of a time step, and each column stands for a certain metric.

**Comment by TrinhDinhPhuc** [comment]
For that, I know. Please reveal your original data with me. Maybe you can send it via my email: phuccoi996@gmail.com 
Thank you!!!

**Comment by NiuChH** [comment]
Sorry, we can only disclose the desensitized data (as is in the repository), because the original data involves some confidentiality problem. I hope you can understand that.

**Comment by TrinhDinhPhuc** [comment]
Revealing the original data shows the effectiveness of OmniAnomaly.

**Comment by TrinhDinhPhuc** [comment]
You should reveal the dataset, at least to me
