### ISSUE TITLE
Is there any way to train OmniAnomaly for multiple servers?

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [smallcowbaby/OmniAnomaly#12]
As I read your paper. OmniAnomaly can only process data of one server. Now I have a data center with several servers how can I train N-servers using OmniAnomaly parallelly?

**Comment by TrinhDinhPhuc** [comment]
Any multi tasking learning techniques can apply for Omnianomaly?

**Comment by NiuChH** [comment]
We didn't investigate that in our project, but we will be happy to see the result if you are willing to experiment on that.
