### ISSUE TITLE
What does anomaly interpretation use for?

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [smallcowbaby/OmniAnomaly#13]
I read the paper but still dont get what you do with anomaly interpretation. Could you give me an example using Server Machine Dataset?

**Comment by TrinhDinhPhuc** [comment]
Please answer @NiuChH

**Comment by NiuChH** [comment]
For example, in the first line of the file `interpretation_label/machine-1-1.txt`, it says,

```
15849-16368:1,9,10,12,13,14,15
```

It means that the first anomaly in file `machine-1-1` is from line 15849 to line 16368, and that the indexes of the dimensions that contribute to this anomaly are `1,9,10,12,13,14,15`.
