### ISSUE TITLE
How can I install tensorflow 1.12.0?

### ISSUE THREAD

**Issue by Hostilitility** [smallcowbaby/OmniAnomaly#14]
pip install tensorflow-gpu==1.12.0

ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.12.0 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0)
ERROR: No matching distribution found for tensorflow-gpu==1.12.0

Seems that version 1.12.0 is not longer provided by pip

**Comment by NiuChH** [comment]
Hi Hostilitility,
tensorflow-gpu 1.12.0 is available only for Python 64-bit 2.7, 3.3, 3.4, 3.5, 3.6 for Linux, so I guess you are probably using Python 3.7 or 3.8, or Python 32-bit. 
As we mentioned in README, please use Python 64-bit 3.5 or 3.6 instead.
