### ISSUE TITLE
Update to Code

### ISSUE THREAD

**Issue by swissbeats93** [smallcowbaby/OmniAnomaly#2]
I'm getting a lot of errors when I try running the code for all three datasets, particularly:

1. Tensorflow is raising a few deprecation warnings because they updated their API. Can you carry out the updates to your code (tf.GraphKeys & tf.train.AdamOptimizer)
2. the file 'machine-1-1' is breaking the entire code. For the SMD this is because there is no folder named test_label inside ServerMachineDataset (The test_labels that is there is inside data and it is empty). For the other two datasets, a NoneType error is raised because I'm guessing it doesn't know which folder to reference for the files or it's referencing the wrong folder

**Comment by NiuChH** [comment]
1. Our code is compatible with TensorFlow 1.12.0 (we have fixed it in `requirements.txt`). Sorry, we cannot update it to a more recent version, due to the dependency on TensorFlow-probability 0.5.0.
2. The error introduced by `test_labels` directory name has been fixed in a recent commit.

**Comment by swissbeats93** [comment]
Maybe just create a conda environment for everything. That way when people test the code they can do it in an isolated environment

**Comment by NiuChH** [comment]
Yes, we do encourage people to create to run the code in an isolated environment. That's why `virtualenv` is recommended in README. You can use it by
```shell
virtualenv <env_name>
source <env_name>/bin/activate
pip install -r requirements.txt
```

And there are equivalent commands for `conda`. You can use either way to build an isolated python environment.
