### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'GraphKeys' 

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [smallcowbaby/OmniAnomaly#3]
I am facing this error `AttributeError: module 'tensorflow' has no attribute 'GraphKeys'`. Even, I installed tensorflow version as the requirement.

**Comment by yzmean** [comment]
You could try to replace '>=' to '==' in requirement.txt .  That's my solution.

**Comment by TrinhDinhPhuc** [comment]
> You could try to replace '>=' to '==' in requirement.txt . That's my solution.

You mean I should reinstall `tensorflow-gpu`?

**Comment by TrinhDinhPhuc** [comment]
i changed the tensorflow version to 13.0.2rc and it worked

**Comment by colakburak** [comment]
@TrinhDinhPhuc I was having the same issue, I am guessing you are using newer versions of the tensorflow so you need to import tensorflow as follows: "from tensorflow.compat.v1 import tf"
