### ISSUE TITLE
No such file or directory: 'processed/MSL_train.pkl

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [smallcowbaby/OmniAnomaly#7]
I run this command:
"_`python main.py  --dataset='MSL' --max_epoch=20`_" and I got this error

```
Traceback (most recent call last):
  File "main.py", line 220, in <module>
    main()
  File "main.py", line 97, in main
    test_start=config.test_start)
  File "/media/harry/harry/ML/LSTM/OmniAnomaly/omni_anomaly/utils.py", line 59, in get_data
    f = open(os.path.join(prefix, dataset + '_train.pkl'), "rb")
IOError: [Errno 2] No such file or directory: 'processed/MSL_train.pkl
```

Please help me, How can I run Server Machine Dataset?

**Comment by NiuChH** [comment]
Hi TrinhDinhPhuc,
Did you run `python data_preprocess.py <dataset>` before `python main.py --dataset=<dataset>`?
You need to download and process the data (with`data_preprocess.py`), before you use it.
