### ISSUE TITLE
OmniAnomaly is unsupervised learning method?

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [smallcowbaby/OmniAnomaly#9]
As I have read the paper. The OmniAnomaly is an unsupervised learning method, however, your Server Machine dataset has labels?

**Comment by TrinhDinhPhuc** [comment]
Please answer me...

**Comment by NiuChH** [comment]
Hi TrinhDinhPhuc,
Sorry for being late. The _test-label_ in the _Server Machine Dataset_ is used for the test of the anomaly detection experiment, and the _interpretation-label_ is for the interpretation experiments (see section 4.5). Note that we use them only for testing and not for training.

**Comment by TrinhDinhPhuc** [comment]
Thank you for making it clearer!
